<?php
/*******************************************************************************
 * Copyright (c) 2017.
 * this file created in printing-office project
 * framework: Yii2
 * license: GPL V3 2017 - 2025
 * Author:amintado@gmail.com
 * Company:shahrmap.ir
 * Official GitHub Page: https://github.com/amintado/printing-office
 * All rights reserved.
 ******************************************************************************/

/**
 * Created by PhpStorm.
 * User: amin__000
 * Date: 9/19/2017
 * Time: 4:16 PM
 */

namespace amintado\slider\widgets;


use yii\base\Widget;

class SliderSettingsHelpWidget extends Widget
{
public $header='help';
public $content='';
public $id='';
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        return $this->render('@vendor/amintado/yii2-module-slider/views/widget/settings_helps.php',
            [
                'header'=>$this->header,
                'content'=>$this->content,
                'id'=>$this->id
            ]
            );
    }
}