<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cancel' => '',
    'Confirmation' => '',
    'Information' => '',
    'Ok' => '',

    'ID'=>'شناسه',
    'Name'=>'نام',
    'Description'=>'توضیحات',
    'Hash ID'=>'کد اسلاید',
    'Position'=>'مکان ابزارک',
    'Css ID'=>'آی دی تگ (گره)',
    'Css Class'=>'اسامی کلاس سفارشی',
    'Css Style'=>'کد اسلاید سفارشی',
    'Html Class'=>'اسامی کلاس سفارشی',
    'Html Style'=>'کد اسلاید سفارشی',
    'Data Ls'=>'کد انیمیشن',
    'Composer ID'=>'شناسه قاب(Composer)',
    'Bg'=>'پشت زمینه',
    'Slide Composers'=>'قاب اسلایدر',
    'Create Slide Composer'=>'ایجاد قاب جدید',
];
